In [1]:
import pandas as pd
from sqlalchemy import create_engine

In [2]:
csv_inegi = "./Resources/csv/BIE_BIE20190523193335.csv"

In [3]:
PIB_df = pd.read_csv(csv_inegi,encoding ='latin1')

In [4]:
PIB_df.head(5)

,Entidad,Sector,2018/01,2018/02,2018/03,2018/04,2018/05,2018/06,2018/07,2018/08,2018/09,2018/10,2018/11,2018/12,2019/01
0,Aguascalientes,Minería,71.581928,74.538138,81.759683,72.966245,76.021630,67.741930,70.577510,75.160746,73.241484,71.103056,78.240948,67.380510,61.900116
1,Aguascalientes,"Generación, transmisión y distribución de ener...",123.135766,125.902232,116.336919,131.971976,122.666208,134.363338,128.927324,124.895400,135.179778,133.347974,142.452951,126.612567,127.888741
2,Aguascalientes,Construcción,122.091917,130.383091,126.659724,113.136473,115.405914,108.993267,116.819366,116.504343,117.430186,121.931559,126.966549,118.115246,115.432118
3,Aguascalientes,Industrias manufactureras,156.279936,137.011376,143.705521,130.896569,143.841126,147.869162,123.645452,153.326693,148.927985,161.185942,158.353279,125.159600,127.898922
4,Baja California,Actividades secundarias,119.017000,118.761771,122.218695,120.953159,123.841961,124.877570,127.481205,131.474620,128.187831,133.690253,127.974122,121.101113,128.953189

In [5]:
PIB_df = PIB_df.rename(columns={'Entidad': 'Estado_calculado'})

In [6]:
PIB_df.columns

Index(['Estado_calculado', 'Sector', '2018/01', '2018/02', '2018/03',
       '2018/04', '2018/05', '2018/06', '2018/07', '2018/08', '2018/09',
       '2018/10', '2018/11', '2018/12', '2019/01'],
      dtype='object')

In [7]:
PIB_df['Estado_calculado'] = PIB_df['Estado_calculado'].str.upper()
PIB_df.head()

,Estado_calculado,Sector,2018/01,2018/02,2018/03,2018/04,2018/05,2018/06,2018/07,2018/08,2018/09,2018/10,2018/11,2018/12,2019/01
0,AGUASCALIENTES,Minería,71.581928,74.538138,81.759683,72.966245,76.021630,67.741930,70.577510,75.160746,73.241484,71.103056,78.240948,67.380510,61.900116
1,AGUASCALIENTES,"Generación, transmisión y distribución de ener...",123.135766,125.902232,116.336919,131.971976,122.666208,134.363338,128.927324,124.895400,135.179778,133.347974,142.452951,126.612567,127.888741
2,AGUASCALIENTES,Construcción,122.091917,130.383091,126.659724,113.136473,115.405914,108.993267,116.819366,116.504343,117.430186,121.931559,126.966549,118.115246,115.432118
3,AGUASCALIENTES,Industrias manufactureras,156.279936,137.011376,143.705521,130.896569,143.841126,147.869162,123.645452,153.326693,148.927985,161.185942,158.353279,125.159600,127.898922
4,BAJA CALIFORNIA,Actividades secundarias,119.017000,118.761771,122.218695,120.953159,123.841961,124.877570,127.481205,131.474620,128.187831,133.690253,127.974122,121.101113,128.953189

In [8]:
PIB_df = PIB_df.rename(columns={'Sector': 'Actividad_economica_agragada'})
PIB_df.head()

,Estado_calculado,Actividad_economica_agragada,2018/01,2018/02,2018/03,2018/04,2018/05,2018/06,2018/07,2018/08,2018/09,2018/10,2018/11,2018/12,2019/01
0,AGUASCALIENTES,Minería,71.581928,74.538138,81.759683,72.966245,76.021630,67.741930,70.577510,75.160746,73.241484,71.103056,78.240948,67.380510,61.900116
1,AGUASCALIENTES,"Generación, transmisión y distribución de ener...",123.135766,125.902232,116.336919,131.971976,122.666208,134.363338,128.927324,124.895400,135.179778,133.347974,142.452951,126.612567,127.888741
2,AGUASCALIENTES,Construcción,122.091917,130.383091,126.659724,113.136473,115.405914,108.993267,116.819366,116.504343,117.430186,121.931559,126.966549,118.115246,115.432118
3,AGUASCALIENTES,Industrias manufactureras,156.279936,137.011376,143.705521,130.896569,143.841126,147.869162,123.645452,153.326693,148.927985,161.185942,158.353279,125.159600,127.898922
4,BAJA CALIFORNIA,Actividades secundarias,119.017000,118.761771,122.218695,120.953159,123.841961,124.877570,127.481205,131.474620,128.187831,133.690253,127.974122,121.101113,128.953189

In [12]:
rds_connection_string =  "ijumrmphpxjghs:60e1c244346de108f89c7a6cc7d27ef39cd59f3ed35012bf153c18a8d0a32264@ec2-107-20-230-70.compute-1.amazonaws.com:5432/d4m36o9apelhp0"

In [13]:
engine = create_engine(f'postgresql://{rds_connection_string}')

In [14]:
PIB_df.to_sql(name='pib_data', con=engine, if_exists='append', index=False)